services:
  worldtracker.web:
    image: ${DOCKER_REGISTRY-}worldtrackerweb
    build:
      context: .
      dockerfile: WorldTracker.Web/Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - WT_DOTENV_PATH=/app/.env
    env_file:
      - ../.env