services:
  terraform:
    image: hashicorp/terraform:1.5.7
    working_dir: /terraform
    volumes:
      - ../terraform:/terraform
    entrypoint: ["/bin/sh", "-c"]
    command: ["terraform init && terraform apply -auto-approve"]
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}

  worldtracker.web:
    image: devmiguelsr/world-tracker:latest
    build:
      context: .
      dockerfile: WorldTracker.Web/Dockerfile
      args:
        VITE_BASE_URL: "http://ec2-15-228-36-236.sa-east-1.compute.amazonaws.com/api/v1/"
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80

      - WT_JWT_SECRET=${WT_JWT_SECRET}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}

      - WT_OPEN_WEATHER_API_KEY=${WT_OPEN_WEATHER_API_KEY}
      - WT_OPEN_WEATHER_BASE_URL=${WT_OPEN_WEATHER_BASE_URL}
      - WT_REST_COUNTRY_BASE_URL=${WT_REST_COUNTRY_BASE_URL}
    restart: always
    depends_on:
      - terraform