services:
  terraform:
    image: hashicorp/terraform:1.5.7
    working_dir: /terraform
    volumes:
      - ./WorldTracker.Infra.Database/Terraform:/terraform
    entrypoint: ["/bin/sh", "-c"]
    command: ["terraform init && terraform apply -auto-approve"]
    env_file:
      - ./WorldTracker.Infra.Database/.env

  worldtracker.web:
    image: ${DOCKER_REGISTRY-}worldtrackerweb
    build:
      context: .
      dockerfile: WorldTracker.Web/Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - WT_DOTENV_PATH=/app/.env
    env_file:
      - ../.env
    depends_on:
      - terraform